#!/bin/sh
### BEGIN INIT INFO
# Provides:             fullpmis-odoo-server
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Enterprise Resource Management software
# Description:          Open ERP is a complete ERP and CRM software.
### END INIT INFO
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/odoo/FULLPMIS/__base__/odoo/openerp-server
NAME=fullpmis-odoo-server
DESC=fullpmis-odoo-server
CONFIG=/opt/odoo/FULLPMIS/odoo-conf/odoo-server.conf
LOGFILE=/opt/odoo/FULLPMIS/odoo-conf/odoo-server.log
USER=odoo

test -x ${DAEMON} || exit 0

set -e

case "${1}" in
		start)
				echo -n "Starting ${DESC}: "

				start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
						--chuid ${USER} --background --make-pidfile \
						--exec ${DAEMON} -- --config=${CONFIG} \
							--logfile=${LOGFILE} --db-filter=^%d$

				echo "${NAME}."
				;;

		stop)
				echo -n "Stopping ${DESC}: "

				start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
						--oknodo

				echo "${NAME}."
				;;

		restart|force-reload)
				echo -n "Restarting ${DESC}: "

				start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
						--oknodo

				sleep 1

				start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
						--chuid ${USER} --background --make-pidfile \
						--exec ${DAEMON} -- --config=${CONFIG} \
							--logfile=${LOGFILE}

				echo "${NAME}."
				;;

		*)

   N=/etc/init.d/${NAME}
						   --logfile=${LOGFILE}

				echo "${NAME}."
				;;

		stop)
				echo -n "Stopping ${DESC}: "

				start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
						--oknodo

				echo "${NAME}."
				;;

		restart|force-reload)
				echo -n "Restarting ${DESC}: "

				start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
						--oknodo

				sleep 1

				start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
						--chuid ${USER} --background --make-pidfile \
						--exec ${DAEMON} -- --config=${CONFIG} \
							--logfile=${LOGFILE}

				echo "${NAME}."
				;;

		*)
				N=/etc/init.d/${NAME}
				echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
				exit 1
				;;
esac

exit 0
